stages:
  data_ingestion:
    cmd: python src/loan/pipeline/stage_01_data_ingestion_pipeline.py
    deps:
      - src/loan/pipeline/stage_01_data_ingestion_pipeline.py
      - src/loan/constant/database.py
      - src/loan/configuration/mongo_db_connection.py
    outs:
      - artifact/data_ingestion

  data_validation:
    cmd: python src/loan/pipeline/stage_02_data_validation_pipeline.py
    deps:
      - src/loan/pipeline/stage_02_data_validation_pipeline.py
      - config/schema.yaml
      - artifact/data_ingestion
    outs:
      - artifact/data_validation/drift_report/report.yaml

  data_transformation:
    cmd: python src/loan/pipeline/stage_03_data_preprocesor_pipeline.py
    deps:
      - src/loan/pipeline/stage_03_data_preprocesor_pipeline.py
      - src/loan/constant/trainingpipeline/__init__.py
      - artifact/data_ingestion/data_ingestion
      - artifact/data_validation/drift_report
    outs:
      - artifact/data_transformation

  model_trainer:
    cmd: python src/loan/pipeline/stage_04_model_training_pipeline.py
    deps:
      - src/loan/pipeline/stage_04_model_training_pipeline.py
      - src/loan/ml/model/model.py
      - params.yaml
      - artifact/data_transformation
    params:
      - BATCH_SIZE
      - EPOCHS
      - OPTIMIZER
      - LOSS
      - METRIC
    outs:
      - artifact/model_trainer/trained_model
  
  model_evaluation:
    cmd: python src/loan/pipeline/stage_05_model_evaluatio_pipeline.py
    deps:
      - src/loan/pipeline/stage_05_model_evaluatio_pipeline.py
      - params.yaml
      - src/loan/components/model_evaluation.py
      - artifact/data_ingestion/data_ingestion
      - artifact/data_transformation/transformed_object
      - artifact/model_trainer/trained_model
    params:
      - BATCH_SIZE
      - EPOCHS
      - OPTIMIZER
      - LOSS
      - METRIC
    outs:
      - artifact/model_evaluation
      - scores.json
          cache: False


