
columns:
  - Income: int
  - Age: int
  - Experience: int
  - Married/Single: category
  - House_Ownership: category
  - Car_Ownership: category
  - Profession: category
  - CITY: category
  - STATE: category
  - CURRENT_JOB_YRS: int
  - CURRENT_HOUSE_YRS: int
  - Risk_Flag: int

categorical_columns:
  - Married/Single
  - House_Ownership
  - Car_Ownership
  - Profession
  - CITY
  - STATE


numerical_columns:
  - Income
  - Age
  - Experience
  - CURRENT_JOB_YRS
  - CURRENT_HOUSE_YRS
  - Risk_Flag
